# config.yaml
program: train.py
method: bayes
name: muv_sweep
metric:
  goal: maximize
  name: test/roc_auc
parameters:
  batch_size: 
    values: [64,128]
  lr:
    max: 0.0001
    min: 0.000001
  max_epoch:
    values: [20,40]
  weight_decay:
    max: 0.001
    min: 0.0000001
command:
  - bash
  - shells/finetune/finetune-molnet-muv.sh